CREATE DATABASE [keyser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'keyser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\keyser.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'keyser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\keyser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [keyser].[dbo].[sp_fulltext_database] @action = 'enable'
end
ALTER DATABASE [keyser] SET ANSI_NULL_DEFAULT OFF 
ALTER DATABASE [keyser] SET ANSI_NULLS OFF 
ALTER DATABASE [keyser] SET ANSI_PADDING OFF 
ALTER DATABASE [keyser] SET ANSI_WARNINGS OFF 
ALTER DATABASE [keyser] SET ARITHABORT OFF 
ALTER DATABASE [keyser] SET AUTO_CLOSE OFF 
ALTER DATABASE [keyser] SET AUTO_SHRINK OFF 
ALTER DATABASE [keyser] SET AUTO_UPDATE_STATISTICS ON 
ALTER DATABASE [keyser] SET CURSOR_CLOSE_ON_COMMIT OFF 
ALTER DATABASE [keyser] SET CURSOR_DEFAULT  GLOBAL 
ALTER DATABASE [keyser] SET CONCAT_NULL_YIELDS_NULL OFF 
ALTER DATABASE [keyser] SET NUMERIC_ROUNDABORT OFF 
ALTER DATABASE [keyser] SET QUOTED_IDENTIFIER OFF 
ALTER DATABASE [keyser] SET RECURSIVE_TRIGGERS OFF 
ALTER DATABASE [keyser] SET  DISABLE_BROKER 
ALTER DATABASE [keyser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
ALTER DATABASE [keyser] SET DATE_CORRELATION_OPTIMIZATION OFF 
ALTER DATABASE [keyser] SET TRUSTWORTHY OFF 
ALTER DATABASE [keyser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
ALTER DATABASE [keyser] SET PARAMETERIZATION SIMPLE 
ALTER DATABASE [keyser] SET READ_COMMITTED_SNAPSHOT OFF 
ALTER DATABASE [keyser] SET HONOR_BROKER_PRIORITY OFF 
ALTER DATABASE [keyser] SET RECOVERY SIMPLE 
ALTER DATABASE [keyser] SET  MULTI_USER 
ALTER DATABASE [keyser] SET PAGE_VERIFY CHECKSUM  
ALTER DATABASE [keyser] SET DB_CHAINING OFF 
ALTER DATABASE [keyser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
ALTER DATABASE [keyser] SET TARGET_RECOVERY_TIME = 60 SECONDS 
ALTER DATABASE [keyser] SET DELAYED_DURABILITY = DISABLED 
ALTER DATABASE [keyser] SET ACCELERATED_DATABASE_RECOVERY = OFF  
ALTER DATABASE [keyser] SET QUERY_STORE = OFF
ALTER DATABASE [keyser] SET  READ_WRITE 
