CREATE TABLE [keyser].[dbo].[dbms](
	[dbms] [varchar](50) NOT NULL,
 CONSTRAINT [PK_dbms] PRIMARY KEY CLUSTERED 
(
	[dbms] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]



